# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Crownlabs"
theme = "syna"
enableGitInfo = true
version = "0.16.2"

# Google Analytics tracking
googleAnalytics = ""

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "CrownLabs"
  description = "Remote laboratories for everyone"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "logobkg.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "logobkg.png"
    favicon_svg = "logobkg.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
#0 54 118
    primary = "#003676"
#    primary = "#00838F"
#   secondary = "#ffffff"
    secondary = "#868e96"
#    success = "#ffffff"
    success = "#008f54"
#    info = "#ffffff"
    info = "#00c9dc"
#    warning = "#ffffff"
    warning = "#fdf314"
#    danger = "#ffffff"
    danger = "#dc1200"
#    light = "#ffffff"
    light = "#f8f9fa"
    dark = "#343a40"
#0 54 118
#    dark = "#003676"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
#[[menu.main]]
#  url = "/"
#  name = "Home"
#  weight = 10

[[menu.main]]
  url = "/about"
  name = "About"
  weight = 20

[[menu.main]]
  url = "/contact"
  name = "Contacts"
  weight = 30

[[menu.main]]
  url = "/contributors"
  name = "Contribute"
  weight = 40

[[menu.main]]
  url = "/calendar"
  name = "Calendar"
  weight = 50

[[menu.main]]
  url = "/resources"
  name = "Resources"
  weight = 50

[[menu.main]]
  url = "/learning"
  name = "Learning"
  weight = 60

[[menu.main]]
  url = "/seminars"
  name = "Seminars"
  weight = 70

#[[menu.main]]
#  url = "https://crownlabs.polito.it"
#  name = "Login @Polito"
#  weight = 30

[[menu.footer]]
  url = "/contact"
  name = "Email"
  weight = 30

[[menu.footer]]
  url = "https://crown-team-group.slack.com"
  name = "Slack"
  weight = 30

[[menu.footer]]
  url = "https://www.youtube.com/playlist?list=PLTAfidx4guQIIPZVaEn8H_hfSTFJ5VQDu"
  name = "Youtube"
  weight = 30

[[menu.copyright_footer]]
  url = ""
  name = "Politecnico di Torino, 2020"
#  name = "© Politecnico di Torino, 2020"
  weight = 10

#[[menu.copyright_footer]]
#  url = "#"
#  name = "Another Link"
#  weight = 30

#[[menu.footer_social]]
#  weight = 20
#  name = "facebook"
#  pre = "fab fa-facebook-f"
#  url = "#"

#[[menu.footer_social]]
#  weight = 30
#  name = "linkedin"
#  pre = "fab fa-linkedin-in"
#  url = "#"

[[menu.footer_social]]
  weight = 30
  name = "slack"
  pre = "fab fa-slack"
  url = "https://crown-team-group.slack.com"

[[menu.footer_social]]
  weight = 30
  name = "github"
  pre = "fab fa-github"
  url = "https://github.com/netgroup-polito/crownlabs/"

[[menu.footer_social]]
  weight = 30
  name = "youtube"
  pre = "fab fa-youtube"
#  url = "https://youtu.be/i7fqga7xQv0"
  url = "https://www.youtube.com/playlist?list=PLTAfidx4guQIIPZVaEn8H_hfSTFJ5VQDu"

