apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      automountServiceAccountToken: false
      containers:
      - name: website
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 25m
            memory: 100Mi
