{{- if .Values.gatewayApiMode }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: website
  labels:
    app: website
    crownlabs.polito.it/public-route: "true"
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.hostName }}
  hostnames:
  - {{ .Values.hostName | quote }}
  {{- end }}
  parentRefs:
  - name: {{ .Values.gateway.name | default "crownlabs-main" | quote }}
    kind: Gateway
    group: gateway.networking.k8s.io
    {{- if .Values.gateway.sectionName }}
    sectionName: {{ .Values.gateway.sectionName | quote }}
    {{- end }}
    {{- if .Values.gateway.namespace }}
    namespace: {{ .Values.gateway.namespace | quote }}
    {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ""
      kind: Service
      name: website
      port: 80
      weight: 1
{{- end }}
